### ISSUE TITLE
use it to upsert into vector db and not the srt

### ISSUE THREAD

**Issue by flyfir248** [AIFame/boteach#6]

**Comment by flyfir248** [comment]
Can u explain what u mean here exactly ?

**Comment by Nasfame** [comment]
@flyfir248 we already discussed, lets put the transcript not the srl

**Comment by flyfir248** [comment]
can u add a requirements.txt for libraries installations ??

**Comment by Nasfame** [comment]
@flyfir248 picking up the tasks, lets catchup on the call tomorrow
